language: python
python:
  - 2.7
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - sudo apt-get install gfortran google-perftools
  - export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
  - pip install --upgrade pip
  - pip install --upgrade cython pytest pytest-cov coveralls
install:
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=varz --cov-report term-missing
after_success:
  - coveralls
