language: python
python:
  - 2.7
  - 3.6
before_install:
  - sudo apt-get install gfortran
  - pip install --upgrade pip
  - pip install --upgrade cython pytest pytest-cov coveralls
install:
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=varz --cov-report term-missing
after_success:
  - coveralls
