language: python
python:
  - 3.6
  - 3.7
before_install:
  - sudo apt-get install gfortran google-perftools
  - export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
install:
  - pip install --upgrade pip
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=varz --cov-report term-missing
after_success:
  - coveralls
